repos:
-   repo: local
    hooks:
    -   id: yapf
        name: yapf
        entry: yapf -i -r --style=.style.yapf
        exclude: '^alembic*'
        language: system
        types: [python]
        
    -   id: flake8
        name: flake8
        entry: flake8 --config=.flake8
        exclude: '^alembic*'
        language: system
        types: [python]

    -   id: mypy
        name: mypy
        entry: mypy 
        exclude: '^alembic*'
        language: system
        types: [python]
